version: '3'

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkinscompose
    ports:
    - "50000:50000"
    - "8880:8080"
    volumes:
    - ../volumes/jenkins:/var/jenkins_home
    networks:
    - docker_network

  ubuntu_slave:
    depends_on:
      - jenkins
    container_name: ubuntucompose
    environment:
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    build:
      context: ../dockerfiles/slave/
    command: java -jar agent.jar -jnlpUrl http://3.67.78.198:8880/computer/slave/jenkins-agent.jnlp -secret 1ee21755493d27599788fbb4ef457b5e2f57e67658d3ddb42170f96459a64654 -workDir "/home/"
    networks:
    - docker_network

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactorycompose
    volumes:
    - ../volumes/artifactory:/var/opt/jfrog/artifactory
    ports:
    - "8081:8081"
    - "8082:8082"
    networks:
    - docker_network

  selenium_hub:
    image: selenium/hub
    container_name: selenium-hubcompose
    ports:
    - "4444:4444"
    networks:
    - docker_network

  firefox:
    image: selenium/node-firefox
    container_name: firefoxcompose
    depends_on:
    - selenium_hub
    environment:
    - HUB_HOST=selenium-hubcompose
    - HUB_PORT=4444 
    networks:
    - docker_network

networks:
  docker_network:
    driver: bridge